# Pmod JB (Left)
set_property PACKAGE_PIN V8 [get_ports {MBL_A}]
set_property PACKAGE_PIN W8 [get_ports {MBL_B}]
set_property PACKAGE_PIN U7 [get_ports {MFL_A}]
set_property PACKAGE_PIN V7 [get_ports {MFL_B}]
set_property PACKAGE_PIN Y7 [get_ports {SBL_A}]
set_property PACKAGE_PIN Y6 [get_ports {SBL_B}]
set_property PACKAGE_PIN V6 [get_ports {SFL_A}]
set_property PACKAGE_PIN W6 [get_ports {SFL_B}]

# Pmod JD (Right)
set_property PACKAGE_PIN T14 [get_ports {MBR_B}]
set_property PACKAGE_PIN T15 [get_ports {MBR_A}]
set_property PACKAGE_PIN P14 [get_ports {MFR_B}]
set_property PACKAGE_PIN R14 [get_ports {MFR_A}]
set_property PACKAGE_PIN U14 [get_ports {SBR_B}]
set_property PACKAGE_PIN U15 [get_ports {SBR_A}]
set_property PACKAGE_PIN V17 [get_ports {SFR_B}]
set_property PACKAGE_PIN V18 [get_ports {SFR_A}]

set_property IOSTANDARD LVCMOS33 [get_ports {MFL_A}]
set_property IOSTANDARD LVCMOS33 [get_ports {MFL_B}]
set_property IOSTANDARD LVCMOS33 [get_ports {SFL_A}]
set_property IOSTANDARD LVCMOS33 [get_ports {SFL_B}]
set_property IOSTANDARD LVCMOS33 [get_ports {MFR_A}]
set_property IOSTANDARD LVCMOS33 [get_ports {MFR_B}]
set_property IOSTANDARD LVCMOS33 [get_ports {SFR_A}]
set_property IOSTANDARD LVCMOS33 [get_ports {SFR_B}]
set_property IOSTANDARD LVCMOS33 [get_ports {MBL_A}]
set_property IOSTANDARD LVCMOS33 [get_ports {MBL_B}]
set_property IOSTANDARD LVCMOS33 [get_ports {SBL_A}]
set_property IOSTANDARD LVCMOS33 [get_ports {SBL_B}]
set_property IOSTANDARD LVCMOS33 [get_ports {MBR_A}]
set_property IOSTANDARD LVCMOS33 [get_ports {MBR_B}]
set_property IOSTANDARD LVCMOS33 [get_ports {SBR_A}]
set_property IOSTANDARD LVCMOS33 [get_ports {SBR_B}]
